---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus
      version: "20.1.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: default
      interval: 1m
  test:
    enable: true
    ignoreFailures: true
  values:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
