---
apiVersion: v1
kind: Namespace
metadata:
  name: argolabs
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus
  namespace: argolabs
spec:
  interval: 1m0s
  url: https://prometheus-community.github.io/helm-charts
