apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons
  namespace: default
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    path: argo-core/applications
    repoURL: https://github.com/retaildevcrews/argo-labs.git
    targetRevision: https://github.com/retaildevcrews/argo-labs.git
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
