apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons
  namespace: argocd
spec:
  generators:
      - clusters:
          selector:
            matchLabels:
              argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{name}}-root'
      labels:
       cluster-id: '{{name}}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/retaildevcrews/argo-labs.git
          targetRevision: 'pragmatical/argolabs-start'
          ref: values
        - repoURL: https://github.com/retaildevcrews/argo-labs.git
          targetRevision: 'pragmatical/argolabs-start'
          path: cluster-add-ons/single-app-of-apps-per-cluster/clusters/{{name}}/apps
          helm:
            parameters:
            - name: 'spec.destination.server'
              value: '{{server}}'
            - name: 'spec.destination.namespace'
              value: 'addons'
            - name: 'clusterName'
              value: '{{name}}'
            valueFiles:
            - $values/cluster-add-ons/single-app-of-apps-per-cluster/clusters/{{name}}/values.yaml
      destination:
        name: 'in-cluster'
        namespace: 'argocd'
      syncPolicy:
        automated:
           prune: false
           selfHeal: true
        retry:
          limit: 3
        syncOptions:      
        - CreateNamespace=true
