apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-sample-flux
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/retaildevcrews/argo-labs.git'
    path: flamingo/fluxapps
    targetRevision: pragmatical/argolabs-start
  destination:
    namespace: argolabs
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - FluxSubsystem=true
