configs:
  #rbac:
    # policy.default: 'role:readonly'
  cm:
    # users.anonymous.enabled: "true"
    timeout.reconciliation: 10s
  params:
    # server.insecure: true
    application.namespaces: "*"
  repositories:
    gitops:
      url: https://github.com/retaildevcrews/argo-labs.git
      name: gitops
      type: git

global:
  nodeSelector:
    kubernetes.azure.com/mode: user

redis-ha:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "prometheus"
      additionalLabels:
        release: prometheus

controller:
  replicas: 1
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "prometheus"
      additionalLabels:
        release: prometheus

server:
  autoscaling:
    enabled: true
    minReplicas: 10
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "prometheus"
      additionalLabels:
        release: prometheus
  resources:
   limits:
     cpu: 1000m
     memory: 2048Mi
   requests:
     cpu: 500m
     memory: 1024Mi

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "prometheus"
      additionalLabels:
        release: prometheus
  resources:
   limits:
     cpu: 1000m
     memory: 2048Mi
   requests:
     cpu: 500m
     memory: 1024Mi

applicationSet:
  replicaCount: 2
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "prometheus"
      additionalLabels:
        release: prometheus
