configs:
  #rbac:
    # policy.default: 'role:readonly'
  cm:
    # users.anonymous.enabled: "true"
    timeout.reconciliation: 10s
  params:
    # server.insecure: true
    application.namespaces: "*"
  repositories:
    gitops:
      url: https://github.com/retaildevcrews/argo-labs.git
      name: gitops
      type: git
redis-ha:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "prometheus"
      additionalLabels: 
        release: prometheus      

controller:
  replicas: 1
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "prometheus"
      additionalLabels: 
        release: prometheus      

server:
  autoscaling:
    enabled: true
    minReplicas: 2
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "prometheus"
      additionalLabels: 
        release: prometheus

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "prometheus"
      additionalLabels: 
        release: prometheus      

applicationSet:
  replicaCount: 2
  metrics:
    enabled: true  
    serviceMonitor:
      enabled: true
      namespace: "prometheus"
      additionalLabels: 
        release: prometheus
      