configs:
  #rbac:
    # policy.default: 'role:readonly'
  cm:
    # users.anonymous.enabled: "true"
    timeout.reconciliation: 180s
  params:
    # server.insecure: true
    application.namespaces: "*"
    server.enable.gzip: true
    controller.status.processors: 20
    controller.operation.processors: 10

  repositories:
    gitops:
      url: https://github.com/retaildevcrews/argo-labs.git
      name: gitops
      type: git

global:
  nodeSelector:
    kubernetes.azure.com/mode: user

redis-ha:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "prometheus"
      additionalLabels:
        release: prometheus

controller:
  replicas: 5
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "prometheus"
      additionalLabels:
        release: prometheus

server:
  autoscaling:
    enabled: true
    minReplicas: 10
    maxReplicas: 20
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "prometheus"
      additionalLabels:
        release: prometheus
  # env:
  #   - name: ARGOCD_GRPC_MAX_SIZE_MB
  #     value: "400"
  resources:
   limits:
     cpu: 2000m
     memory: 4096Mi
   requests:
     cpu: 1000m
     memory: 2048Mi

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 5
    maxReplicas: 10
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "prometheus"
      additionalLabels:
        release: prometheus
  resources:
   limits:
     cpu: 1000m
     memory: 2048Mi
   requests:
     cpu: 500m
     memory: 1024Mi

applicationSet:
  replicaCount: 5
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "prometheus"
      additionalLabels:
        release: prometheus
