apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: infra
  sources:
  - repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: 5.36.10
    chart: argo-cd
    helm:
      valueFiles:
      - $values/argo-400k/gitops/management/argocd/argocd-values.yaml
  - repoURL: https://github.com/retaildevcrews/argo-labs.git
    targetRevision: joaquinrz-argo400k
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    retry:
      limit: -1 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
