configs:
  rbac:
    policy.default: 'role:readonly'
  cm:
    users.anonymous.enabled: "true"
    # Timeout to discover if a new manifests version got published to the repository. 3 minutes by default.
    # Impacts how much time application controller queue processors have to clear the queue before the next reconciliation cycle.
    timeout.reconciliation: 180s
  params:
    server.insecure: true
    application.namespaces: "*"
    server.enable.gzip: true
    # The number of queue processors to process application reconciliation queue. 20 by default
    controller.status.processors: 20
    # The number of queue processors to process app syncing queue. 10 by default
    controller.operation.processors: 10

  repositories:
    gitops:
      url: https://github.com/retaildevcrews/argo-labs.git
      name: gitops
      type: git

global:
  nodeSelector:
    kubernetes.azure.com/mode: user

redis-ha:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "prometheus"
      additionalLabels:
        release: prometheus
  haproxy:
    metrics:
      enabled: true

controller:
  # This replica count affects performance related to the number of Clusters that Argo is managing.
  replicas: 1
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "prometheus"
      additionalLabels:
        release: prometheus

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/hostname: argocd.joaquin.dev
    hosts:
    - argocd.joaquin.dev
    tls:
      - secretName: argocd-tls
        hosts:
          - argocd.joaquin.dev
    https: true
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "prometheus"
      additionalLabels:
        release: prometheus
  env:
    # Max size of the server response message in megabytes. Default is 200.
    - name: ARGOCD_GRPC_MAX_SIZE_MB
      value: "800"
  resources:
   limits:
     cpu: 2000m
     memory: 4096Mi
   requests:
     cpu: 1000m
     memory: 2048Mi

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "prometheus"
      additionalLabels:
        release: prometheus
  resources:
   limits:
     cpu: 1000m
     memory: 2048Mi
   requests:
     cpu: 500m
     memory: 1024Mi

applicationSet:
  replicaCount: 2
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "prometheus"
      additionalLabels:
        release: prometheus
