---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-sample-flux-workload
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/retaildevcrews/argo-labs.git'
    path: flux-without-flamingo/fluxapps
    targetRevision: pragmatical/argolabs-start
  destination:
    namespace: argolabs
    name: workload-cluster-1
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - FluxSubsystem=true
      - Replace=true
