global:
  rbac:
    create: true
    pspEnabled: false
alertmanager:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeEtcd:
  enabled: false
kubelet:
  enabled: true
  serviceMonitor:
    cAdvisor: true
kube-state-metrics:
  metricLabelsAllowlist:
  - nodes=[agentpool,node_kubernetes_io_instance-type]
prometheus:
  enabled: true
  prometheusSpec:
    externalLabels:
      region: southcentral
      cluster: management
    retention:
      size: 2GB
grafana:
  enabled: false